//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TweetDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public string user_id { get; set; }
        public string password { get; set; }
        public string fullname { get; set; }
        public string email { get; set; }
        public System.DateTime joined { get; set; }
        public bool active { get; set; }
    }
}
